extism/extism

- .github/workflows/ci.yml
- Cargo.toml
- elixir/.formatter.exs
- elixir/.gitignore
- elixir/README.md
- elixir/lib/extism.ex
- elixir/lib/extism/context.ex
- elixir/lib/extism/native.ex
- elixir/lib/extism/plugin.ex
- elixir/mix.exs
- elixir/mix.lock
- elixir/native/extism_nif/.cargo/config
- elixir/native/extism_nif/Cargo.toml
- elixir/native/extism_nif/src/lib.rs
- elixir/test/extism_test.exs
- elixir/test/test_helper.exs
- ruby/lib/extism/version.rb
- rust/src/context.rs
- rust/src/plugin.rs
This implements the a basic Elixir / Erlang host SDK. I still have some work to do on it this weekend.
* Pull down this branch
* In a different folder create a new elixir project:
`mix new extism_elixir_host && cd extism_elixir_host`
* Link to the local dependency by updating the `deps` in `mix.exs`:
```elixir
defp deps do
[
{:extism, path: "/Users/ben/Code/extism/elixir"}
]
end
```
* Run `mix deps.get`
* Run `mix deps.compile`, this should trigger the rust compilation in the elixir lib depdency
* Run `iex -S mix` to start a REPL.
* Test happy path:
```elixir
iex(1)> manifest = %{ wasm: [ %{ path: "/Users/ben/code/extism/wasm/code.wasm" } ]}
%{wasm: [%{path: "/Users/ben/code/extism/wasm/code.wasm"}]}
iex(2)> {:ok, plugin} = Extism.Plugin.new(manifest)
{:ok,
%Extism.Plugin{
resource: 0, …
```
> Implement Host SDK for Elixir

- runtime/src/sdk.rs
I found this bug when trying to update the Rust PDK: https://github.com/extism/rust-pdk/pull/3
> Fix bug in `extism_plugin_config` when wasi is disabled

- elixir/native/extism_nif/Cargo.toml
- elixir/native/extism_nif/src/lib.rs
We can merge this after we release `rc.6`
> feat(elixir):  use result of set_log_file

- browser/src/index.test.ts
- browser/src/plugin.ts
This also only instantiates the module once and combines `ExtismPlugin` with `ExtismPluginCall`, I can pull out just the new function implementations if that's an issue.
> feat: add var/config functions, merge ExtismPlugin and ExtismPluginCall

- composer.json
Need to include new Context file
> fix(php-sdk): fix the composer file

- cpp/extism.hpp
- extism.go
- node/src/index.ts
- ocaml/lib/extism.ml
- ocaml/lib/extism.mli
The Haskell SDK is updated here: https://github.com/extism/extism/pull/138
> feat: Add support for `allowed_paths` manifest key in SDKs

- java/pom.xml
- java/readme.md
- java/src/main/java/org/extism/sdk/manifest/MemoryOptions.java
- java/src/test/java/org/extism/sdk/ManifestTests.java
- java/src/test/java/org/extism/sdk/PluginTests.java
- java/src/test/java/org/extism/sdk/TestWasmSources.java
- Fix broken javadoc comment
- Add tests for Manifest serilization and refactor tests
- Remove duplicate developer entry in pom.xml
- Add initial readme
Improves #117
> (java-sdk) Add tests for Manifest and polish MemoryOptions

- manifest/schema.json
- manifest/src/lib.rs
- python/tests/test_extism.py
- runtime/Cargo.toml
- runtime/src/context.rs
- runtime/src/function.rs
- runtime/src/lib.rs
- runtime/src/plugin.rs
- runtime/src/plugin_ref.rs
- runtime/src/sdk.rs
- runtime/src/timer.rs
- rust/src/plugin_builder.rs
- Adds `Manifest::timeout_ms` field to specify the plugin timeout in milliseconds
- Sets a 30 second default timeout
> feat: Add option to set timeout for plugin 

- java/src/main/java/org/extism/sdk/Context.java
- java/src/main/java/org/extism/sdk/Extism.java
- java/src/main/java/org/extism/sdk/LibExtism.java
(cherry picked from commit 766090a1aa8340598c643ca01dded16b15c26ba5)
> refactor(java-sdk): Revise API usage

- elixir/native/extism_nif/src/lib.rs
- manifest/src/lib.rs
> chore: use new base64 API, cleanup clippy warnings

- extism.go
- go/main.go
- runtime/build.rs
- runtime/extism.h
See https://discord.com/channels/1011124058408112148/1050087851443888138/1064977577837592739
> fix: use `cgo.Handle` to protect Go pointers being passed to C callbacks

- .github/workflows/ci-java.yml
- java/pom.xml
- java/src/main/java/org/extism/sdk/manifest/ManifestHttpRequest.java
- java/src/main/java/org/extism/sdk/manifest/MemoryOptions.java
- java/src/main/java/org/extism/sdk/wasm/ByteArrayWasmSource.java
- java/src/main/java/org/extism/sdk/wasm/PathWasmSource.java
Hi,
We want to use Extism on our project [Otoroshi](https://github.com/MAIF/otoroshi) but we need to run it on jdk11
This pull request makes everything run smoothly on jdk11
If you have any suggestion about this pull request, i'm open to it
Thanks for your time
> Support jdk11

- zig/examples/basic.zig
- zig/test.zig
> fix(zig-sdk): Fix Example And Test

- java/src/main/java/org/extism/sdk/manifest/Manifest.java
- java/src/test/java/org/extism/sdk/ManifestTests.java
Hi people, 
just a small pull request to add support for `allowed_paths` in the Java SDK as it would be awesome to have it in the [Otoroshi project](https://github.com/MAIF/otoroshi).
I hope it's okay for you ;)
Thanks in advance
> feat: Support allowed_paths in the Java SDK

- runtime/src/pdk.rs
This PR prevents a panic on the host side when an HTTP request fails
> fix: improve `extism_http_request` error handling

- zig/build.zig
Fixes breaking build system changes introduced in ziglang/zig#15245
> fix(zig-sdk): Fix build

- runtime/src/pdk.rs
- Makes it so requests to a host that isn't specified by `allowed_hosts` will fail
- To allow requests to any URL you can set `{allowed_hosts: ["*"]}`
> fix!: disallow http requests by default

- browser/package.json
Publishes the latest changes, including #306
> chore: publish browser host

- dune-project
See https://github.com/ocaml/opam-repository/pull/23806#discussion_r1201772532
> fix(ocaml): update dune-project file

- python/extism/extism.py
This should fix the issue @neuronicnobody ran into with a segfault depending on the scope of the host function definition
> fix(python): store reference to host functions on Plugin

- libextism/API.md
- libextism/README.md
- manifest/src/lib.rs
- runtime/README.md
- runtime/benches/bench.rs
- runtime/build.rs
- runtime/extism.h
- runtime/src/current_plugin.rs
- runtime/src/function.rs
- runtime/src/lib.rs
- runtime/src/sdk.rs
- runtime/src/tests/runtime.rs
C: https://github.com/extism/extism/blob/new-readmes/libextism/README.md
Rust: https://github.com/extism/extism/blob/new-readmes/runtime/README.md
Also includes some small usability improvements I stumbled across when working on the docs
> doc: add `runtime/README.md` and `libextism/README.md` 

- libextism/Cargo.toml
- runtime/Cargo.toml
- rust/Cargo.toml
Cuts a new 0.5.3 release from stable.
> Release: 0.5.3 stable release

- README.md
- browser/README.md
- d/README.md
- dotnet/README.md
- elixir/README.md
- go/README.md
- haskell/README.md
- java/readme.md
- node/README.md
- ocaml/README.md
- php/README.md
- python/README.md
- ruby/README.md
- zig/README.md
Point everything to to new repos. We will eventually remove these subrepos to clean everything up but leaving them for the next month at least.
> docs: Point to readmes

- libextism/README.md
- libextism/example.c
- runtime/build.rs
- runtime/extism.h
Similar to #558 but for libextism
> cleanup: add PTR as an alias for I64 in C API

- runtime/benches/bench.rs
This parameterizes the `reflect` test and calls the `g.throughput` on each data set to get an idea of our roundtrip throughput. (The changes follow the "Throughput Measurements" [1] part of the Criterion guide pretty much to the letter.)
Example output:
```
reflect/reflect 1       time:   [208.57 µs 209.05 µs 209.57 µs]
thrpt:  [298.23 MiB/s 298.97 MiB/s 299.66 MiB/s]
```
[1]: https://bheisler.github.io/criterion.rs/book/user_guide/advanced_configuration.html#throughput-measurements
> refactor(bench): Add throughput information to reflect function.

- .github/workflows/release-dotnet-native.yaml
Seems like the assets now include version numbers in their name
> Update release-dotnet-native.yaml to be resilient against file name changes

- .github/workflows/ci-rust.yml
- extism-maturin/build.rs
Check formatting of all crates to ensure the whole codebase stays formatted.
> ci: check formatting of all crates

- DEVELOPING.md
Describe the release workflow as flowing from tag -> builds -> release.
[**Rendered**](https://github.com/extism/extism/blob/chris/20231120-addd-developing/DEVELOPING.md)
> doc: add DEVELOPING.md with release workflow

- README.md
Just moving this around and changing it up for the beta release.
> docs: Some readme changes on api status

- kernel/src/lib.rs
This cosmetic change to the kernel adds two `u64` types for usage where `Pointer` was used and it is actually something else or is more restrictive (a pointer to the start of a data block (handle) or a relative offset). 
Instead of adding `Offset` to match `Length` I'd prefer to use `u64` directly when referring to those scalars, but not sure if the those types are preferred?
> chore: kernel add Handle and Offset types to differentiate from Pointer

- runtime/src/current_plugin.rs
> feat: add id() to CurrentPlugin

- libextism/.clang-format
- libextism/README.md
- libextism/example.c
Big thanks to @konsumer for reporting the issues!
> fix(libextism): examples and docs

- convert/src/tests.rs
- runtime/src/current_plugin.rs
- runtime/src/pdk.rs
- runtime/src/plugin.rs
- runtime/src/tests/kernel.rs
- runtime/src/tests/runtime.rs
Add support for logtrace in Rust SDK runtime
https://github.com/extism/extism/issues/744 that is a logical step after [this](https://github.com/extism/go-pdk/issues/37)
- [] Documentation added/updated
> feat(runtime): support log_trace in rust-sdk

- runtime/src/sdk.rs
Both [as_ptr][as_ptr] and [as_mut_ptr][as_mut_ptr] are allowed to return a dangling raw pointer when the Vec size is 0.
The idea is that you should guard that read checking the size. This probably works well in most cases, but at the very least in the java-sdk, the JNA machinery tries to be helpful and it dereferences the pointer, causing a SIGSEGV.
The solution is to check if the resulting vector is empty and return null instead. A new, empty vector would be better, but I think that would not solve the problem, because the problem is caused by a new, empty vector in the first place.
Caveat: this might break consumers downstream.
On the other hand: consumers that do not check for the nInput, nOutput counts are just waiting to explode, like JNA.
This addresses …
> fix: Vec.as_ptr() might return a dangling pointer

- README.md
from https://extism.org/docs/concepts/pdk
> chore: define pdk term in README

- runtime/src/sdk.rs
`extism_compiled_plugin_new` would panic on bad manifest input (there's a test in the python sdk [1] that hits this directly.) Catch the error and set `errmsg` appropriately instead.
Additionally: golf the function pointer casting for the various `plugin_new` calls, with the goal of reducing the number of allocations by leaning on iterator size hints (and reducing the scope of `unsafe{}` use.) This introduces a breaking change. Previously `NULL` values were silently accepted in the `functions**` list; now they fail. This maintains consistency with behavior on "consumed" `ExtismFunction` pointer.
[1]: https://github.com/extism/python-sdk/blob/main/tests/test_extism.py#L50-L53
> fix: remove unwrap() from extism_compiled_plugin_new

- .github/workflows/release.yml
> ci: install android libunwind before build step

- runtime/src/plugin.rs
Previously, code that called a plugin that called a host function that called back into the plugin would hang in an attempt to attain the lock. Switch to `try_lock` so we can surface the error.
(Just noticed this in Discord this AM.)
> fix: throw error on reentrant plugin call
