ruby/lib/extism.rb

There appears to be a situation in which this err can be nil

Safe access to nilable error

---

runtime/src/export.rs

- Makes it so `extism_length(0)` returns 0, as far as I can tell this seems safe
- Returns 0 when a key can't be found

Handle missing config keys without raising an error

---

manifest/src/lib.rs

This makes using `HttpRequest` from the PDK a little nicer

feat: add HttpRequest builder functions

---

.github/workflows/release.yml
manifest/Cargo.toml
node/example.js
node/index.js
node/package.json
python/pyproject.toml
python/setup.cfg
runtime/Cargo.toml
rust/Cargo.toml

Adds automated releases for crates.io, pypi, and npm for Rust, Python, and Node host SDKs respectively.

ci: add host sdk releases 

---

runtime/src/memory.rs

This PR fixes an issue where large allocations are currently causing some arithmetic to wrap which caused a panic.  
This was discovered by calling `http_get` on `youtube.com` from the http example in the Rust PDK

Fix large allocations

---

extism.go
haskell/src/Extism/Manifest.hs
manifest/schema.json
manifest/src/lib.rs
ocaml/lib/extism.ml
ocaml/lib/extism.mli
runtime/Cargo.toml
runtime/src/export.rs
runtime/src/plugin.rs

- Adds `allowed_hosts` to the manifest
- If there are any `allowed_hosts` then `extism_http_request` checks to make sure a URL's host is listed before performing the request
One thing to note: I have a branch that also adds `allowed_dirs`, but I'm not sure if that's something I want to include. We had kinda talked about not supporting filesystem access, which simplifies everything. The reason I ended up making that branch is when experimenting with `python.wasm` it seemed to require the current directory to be preopened. Since Python plugin support is a long ways off and we can probably hack around the filesystem requirement it's probably best to leave it `allowed_dirs` out until we know if we'll need it.

Add `allowed_hosts` configuration option

---

.github/workflows/ci.yml
runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/plugin.rs
runtime/src/sdk.rs

Also avoids instantiating a wasi context for plugins where wasi is disabled.

Add `nn` feature to enable `wasi-nn` for plugins that enable WASI

---

extism.go
go/main.go
haskell/src/Extism.hs
node/index.js
ocaml/lib/extism.ml
php/src/Context.php
php/src/extism.h
python/extism/__init__.py
python/extism/extism.py
ruby/lib/extism.rb
runtime/extism.h
runtime/src/sdk.rs
rust/src/bindings.rs
rust/src/lib.rs

Adds a new Host SDK call `extism_version` which returns the version string.

Add `extism_version` to Host SDK and all clients

---

elixir/native/extism_nif/Cargo.toml

I thought this would look for the local path then fallback to the crates.io version. Ideally we want this to be conditional somehow.

Fix Elixir cargo dependency

---

.github/actions/extism/action.yml
.github/workflows/ci.yml

Creates a new workflow for each language, allowing all languages to run tests even when one fails
Also disables running on `push` (but once this is merged the workflow can be manually triggered)

ci: create workflow for each language

---

runtime/src/context.rs
runtime/src/pdk.rs
runtime/src/plugin.rs
rust/src/context.rs
rust/src/plugin.rs

This is kind of hacky but until we have an established way of encoding complex types in memory it seems good enough

feat: add `extism_http_status_code` to get the status code of the last HTTP request + fixes for clippy

---

elixir/test/extism_test.exs
python/tests/test_extism.py
ruby/test/test_extism.rb

Related to https://github.com/extism/extism/pull/82
Ensures we have unicode inputs in our SDK tests. We should probably get unicode in the output as well

test: Make sure we have unicode in the SDK tests

---

node/src/index.ts
node/tests/index.test.ts

Properly calculate the length of utf-8 inputs. I'll work on getting unicode chars into our other tests as well and see if we need to fix any other SDKs

fix(node-sdk): Properly calculate length of utf-8 inputs

---

runtime/Cargo.toml
runtime/src/pdk.rs
runtime/src/sdk.rs

- Updates codebase to use the latest version of wasmtime, wasmtime-wasi and wasmtime-wasi-nn
- Allows functions with no return values to be called, this provides basic support for `_start` functions
- For now `_start` functions called by extism still need to use the extism input/output functions instead of the command line arguments

Updates for wasmtime/wasmtime-wasi/wasmtime-wasi-nn, basic support for calling `_start` functions

---

elixir/mix.exs

I've tested it in at least as low as 1.12. It just prints out a warning so should be fine if someone wants to use it on an older version.

docs(elixir-sdk): Reduce elixir min version

---

browser/Makefile
browser/package-lock.json
browser/src/index.test.ts

I accidentally published without building. this should help make sure releases are valid

chore: Add Makefile for browser runtime

---

runtime/src/sdk.rs

This bug exists because we didn't change the crate name in the logging registration function, so all of our logs from `extism_runtime` were being filtered out.

fix: update crate name to extism_runtime in logging registration function

---

java/pom.xml
java/src/main/java/org/extism/sdk/LibExtism.java
java/src/test/java/org/extism/sdk/ExtismTest.java

We now resolve the extism library dynamically based on the rules
defined in com.sun.jna.NativeLibrary.
For tests we resolve the library relative to the cwd based on the
jna.library.path system property set to ../target/release.
Improves #117

feat: Java Host SDK

---

java/pom.xml
java/src/main/java/org/extism/sdk/Context.java
java/src/main/java/org/extism/sdk/ExtismException.java
java/src/main/java/org/extism/sdk/LibExtism.java
java/src/main/java/org/extism/sdk/Plugin.java
java/src/main/java/org/extism/sdk/manifest/Manifest.java
java/src/main/java/org/extism/sdk/manifest/ManifestHttpRequest.java
java/src/main/java/org/extism/sdk/manifest/ManifestMemory.java
java/src/main/java/org/extism/sdk/manifest/ManifestWasm.java
java/src/main/java/org/extism/sdk/manifest/ManifestWasmData.java
java/src/main/java/org/extism/sdk/manifest/ManifestWasmUrl.java
java/src/main/java/org/extism/sdk/support/JsonSerializer.java
java/src/main/java/org/extism/sdk/wasm/ByteArrayWasmSource.java
java/src/main/java/org/extism/sdk/wasm/FileBasedWasmSource.java
java/src/main/java/org/extism/sdk/wasm/WasmSource.java
java/src/test/java/org/extism/sdk/ExtismTest.java

- Refactor Plugin
- Make `Plugin` and `Context`  `AutoClosable` to automatically free resources in TWR blocks
- Add missing javadoc
- Upgrade to Junit 5
- Reorganize packages
- Use more meaningful names
- Introduce `ExtismException`
- Make JSON serialization pluggable
- Lower required java version to Java 17
Improves #117

Refactor java-sdk

---

extism.go
haskell/manifest/Extism/Manifest.hs
manifest/schema.json
manifest/src/lib.rs
node/src/index.ts
ocaml/lib/extism.ml
ocaml/lib/extism.mli
python/tests/test_extism.py
runtime/src/manifest.rs
runtime/src/pdk.rs
runtime/src/plugin.rs

- Adds some helper functions for creating a manifest, mostly helpful for the Rust SDK
- Renames `ManifestWasm` to `Wasm`
- Renames `ManifestMemory` to `MemoryOptions`
- `ManifestWasm` and `ManifestMemory` have been marked as deprecated
- Adds an alias from `MemoryOptions::max_pages` to `MemoryOptions::max` in serde specification

feat: Improve usability of manifest types

---

runtime/src/plugin.rs
runtime/src/plugin_ref.rs
runtime/src/sdk.rs

After a closer reading of: https://github.com/WebAssembly/WASI/blob/main/legacy/application-abi.md it looks likes `_start` is expected to be called at most once. This PR automatically reinstantiates a plugin after a call to `_start` so it can be used again.
CI caught a bug with the `extism_version` output which is fixed here: https://github.com/extism/extism/pull/139

fix: Reinstantiate after call to `_start`

---

manifest/schema.json
manifest/src/lib.rs
runtime/src/plugin.rs

Adds ability to make local files available to plugins. Using the Rust SDK:
```rust
let wasm = include_bytes!("code.wasm");
let mut context = Context::new();
let manifest = Manifest::new(vec![Wasm::data(wasm)]).with_allowed_path("/path/on/disk", "/plugin/path");
let plugin = Plugin::new_with_manifest(&mut context, &manifest, false)?;
...
```

feat: add `allowed_paths` to specify preopened directories in WASI

---

runtime/src/plugin.rs

`Dir::from_std_file` works on Linux, but does not work as expected on Windows

fix: use `Dir::open_ambient_dir` instead of `Dir::from_std_file`

---

manifest/src/lib.rs
runtime/src/context.rs
runtime/src/function.rs
runtime/src/lib.rs
runtime/src/pdk.rs
runtime/src/plugin.rs
rust/Cargo.toml
rust/src/lib.rs
rust/src/plugin.rs
rust/src/plugin_builder.rs

- Adds the ability to initialize plugins with additional functions created by the host (only supported by the Rust SDK right now) 
- Adds `PluginBuilder` to the Rust SDK to make it easier to configure all the options
The following example uses `println` from the host to print to stdout from inside the plugin.
Host:
```rust
use extism::*;
fn main() -> Result<(), Error> {
let context = Context::new();
let manifest = Manifest::new([std::path::PathBuf::from("code.wasm")]);
let say_hello = Function::new("say_hello", [ValType::I64], [], |caller, input, _out| {
let internal = caller.data();
let r = internal.memory().get_str(input[0].unwrap_i64() as usize)?;
println!("Hello, {r}!");
Ok(())
});
let mut plugin = PluginBuilder::new(manifest)
.with_function(say_hello)
.with_wasi(true) …
```

feat: Add ability to register host functions with the runtime from the Rust SDK

---

runtime/src/context.rs
runtime/src/plugin.rs

After adding the timer code plugins written in Haskell fail with a timeout when trying to call `hs_init` - this PR fixes the runtime initialization and updates those functions to respect the configured timeout.

fix: use timeouts for language-specific runtime initialization/finalization calls

---

browser/Makefile
browser/build.js
browser/index.html
browser/package-lock.json
browser/package.json
browser/src/plugin.ts
browser/tsconfig.json

closes #160
Goal is not to expose all the WASI functionality, but to just write minimum code to allow PDK targets that require WASI (e.g. tinygo compiled plugins) to work in the browser. We can follow up with allowing the user more control over the WASI environment.

feat: WASI support for browser runtime

---

elixir/mix.exs
elixir/native/extism_nif/Cargo.toml

https://github.com/extism/extism/commit/5c9aa4c90a83542c043c366ba7ebce50e81b3d65
This should work but it doesn't. Error message when including extism 0.2.0 locally:
```
Compiling 4 files (.ex)
error: failed to get `extism` as a dependency of package `extism_nif v0.1.0 (/private/tmp/extism_test/deps/extism/native/extism_nif)`
Caused by:
failed to load source for dependency `extism`
Caused by:
Unable to update /private/tmp/extism_test/deps/rust
Caused by:
failed to read `/private/tmp/extism_test/deps/rust/Cargo.toml`
Caused by:
No such file or directory (os error 2)
== Compilation error in file lib/extism/native.ex ==
** (RuntimeError) calling `cargo metadata` failed.
(rustler 0.26.0) lib/rustler/compiler/config.ex:87: Rustler.Compiler.Config.metadata!/1
(rustler 0.26.0) …
```

fix(elixir-sdk): Release 0.2.0 is broken due to this local path dep

---

runtime/src/memory.rs

If you look at the memory traces it's not really clear what the values are:
```
extism_runtime::memory TRACE 2023-01-23T10:05:16.918413-06:00 - store_u64: 656c626169726176 at offset 25
extism_runtime::memory TRACE 2023-01-23T10:05:16.918418-06:00 - store_u8: 20 at offset 33
extism_runtime::memory TRACE 2023-01-23T10:05:16.918423-06:00 - store_u8: 76 at offset 34
extism_runtime::memory TRACE 2023-01-23T10:05:16.918428-06:00 - store_u8: 61 at offset 35
extism_runtime::memory TRACE 2023-01-23T10:05:16.918433-06:00 - store_u8: 6c at offset 36
extism_runtime::memory TRACE 2023-01-23T10:05:16.918438-06:00 - store_u8: 75 at offset 37
extism_runtime::memory TRACE 2023-01-23T10:05:16.918443-06:00 - store_u8: 65 at offset 38
```
It's hard to tell that the value is hex and the offset is base10. This …

chore: Make memory traces clearer

---

dune-project
extism-manifest.opam
extism.opam

A few changes to the opam files based on the review from https://github.com/ocaml/opam-repository/pull/23018

cleanup: fix opam files according to changes published to opam

---

.github/workflows/browser-ci.yml
browser/jest.config.js
browser/package-lock.json
browser/package.json
browser/src/index.test.ts

Can't quite figure out what is going on. Jest cannot resolves our code fine but can't seem to resolve the NPM module:
```
FAIL  src/index.test.ts
● Test suite failed to run
Cannot find module '@bjorn3/browser_wasi_shim' from 'src/plugin.ts'
Require stack:
src/plugin.ts
src/context.ts
src/index.ts
src/index.test.ts
2 | import { PluginConfig } from './manifest';
3 | //@ts-ignore TODO add types to this library
> 4 | import { WASI, File } from "@bjorn3/browser_wasi_shim";
| ^
5 |
6 | export default class ExtismPlugin {
7 |   moduleData: ArrayBuffer;
at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:425:11)
at Object.<anonymous> (src/plugin.ts:4:1)
at Object.<anonymous> (src/context.ts:2:1)
at Object.<anonymous> (src/index.ts:1:1)
at Object.<anonymous> …
```

test(browser): Comment out test so we stop failure

---

cpp/extism.hpp
extism.go
node/src/index.ts
ocaml/lib/bindings.ml
ocaml/lib/extism.mli
ocaml/lib/function.ml
python/extism/extism.py
runtime/extism.h
runtime/src/function.rs
runtime/src/plugin.rs
runtime/src/sdk.rs
rust/src/lib.rs
rust/src/plugin.rs
rust/src/plugin_builder.rs

- Adds `extism_function_set_namespace` to SDK
- Updates SDKs with host function support to allow setting the namespace for a function

feat: add ability to set host function namespace

---

elixir/native/extism_nif/Cargo.toml
libextism/Cargo.toml
manifest/Cargo.toml
runtime/Cargo.toml
runtime/src/plugin.rs
rust/Cargo.toml

Unsure if now is the best time to do the `extism` crate version bumps, but I figured they'd need to happen at some point in the near future anyways. Happy to revert if there is any opposition. Also, I added back the local `path` property to the Elixir NIF crate manifest. I want to see if this breaks again in CI, or if we can leave it.

chore: update wasmtime to 6.0, bump extism versions

---

runtime/src/timer.rs

fix: remove call to cleanup_timer at exit on windows

---

browser/package-lock.json
browser/package.json
browser/src/plugin.ts

This upgrades the wasi shim and publishes new version of our runtime. Current published version is broken because it relies on a my git branch which has since been merged into the wasi shim.

fix(browser): Fix browser runtime, publish as 0.2.7

---

Cargo.toml
elixir/mix.exs
elixir/native/extism_nif/Cargo.toml

Published this fix as 0.3.2: https://github.com/extism/extism/issues/343
going to disconnect this rust project for the time being. If we want to publish a new elixir client with the new runtime then we must wait until the runtime hit's crates.io

fix(elixir): Fix nif package build and release as 0.3.2

---

runtime/src/plugin.rs

This could also be extended to support other wasmtime-based profiling methods, for now just `perf` is supported.

feat: add EXTISM_PROFILE environment variable to configure profiling

---

dotnet/nuget/Extism.runtime.win.csproj
runtime/Cargo.toml
rust/Cargo.toml

* https://github.com/extism/extism/pull/315
HTTP calls will be disallowed by default now. If you want to enable HTTP you need to specify the hosts that the plug-in is allowed to communicate with. If you want to allow all hosts you can set it to `{allowed_hosts: ["*"]}` in the manifest. However, this isn't recommended unless you have some trust in the plug-in or are controlling the networking by some other means.
* https://github.com/extism/extism/pull/335
In this PR we are creating an implicit context so people don't need to know about it if they don't care. In some languages function signatures have changed to make context an optional argument when creating a plug-in.

release: Bump runtime to 0.4.0

---

ocaml/manifest/extism_manifest.ml
runtime/Cargo.toml

Currently wasmtime `8.0.0` - `10.0.0` are compatible with `extism-runtime`, in the interest of remaining compatible with as many applications as possible, this PR updates the wasmtime version requirement from a single version to a range of acceptable versions.

chore: use a range for wasmtime dependency version

---

runtime/Cargo.toml
runtime/src/plugin.rs
runtime/src/plugin_ref.rs
runtime/src/sdk.rs
rust/src/lib.rs

- Delays instantiation to right before a call by using `instantiate_pre` instead. This fixes an issue with the assemblyscript PDK.
- Makes timeouts only apply to calls
- Also bumps the wasmtime lower-bounds to 10.0, because the return type of the epoch callback has changed

fix: avoid timeout errors outside of `extism_plugin_call`

---

rust/src/lib.rs

Also adds a test that uses `InternalExt` in the host function

fix(rust): ensure InternalExt is exported

---

kernel/build.sh
runtime/build.rs

I think this will fix the issue with CI hanging - this fixes the issue when building Elixir, which seems to be the same as the CI issue

fix: remove call to bash from build.rs

---

runtime/src/manifest.rs
runtime/src/plugin.rs
runtime/src/tests.rs

Just getting my feet wet with the codebase a little bit! I noticed that TOML manifests weren't loading the extism runtime by default while doing a walkthrough. This commit ensures the runtime is loaded and adds a test.
Also, fix a tiny typo in a comment.

fix: toml manifests load the extism runtime

---

runtime/src/current_plugin.rs

@mhmd-azeez pointed out that exposing an option like this can be very useful for debugging if the program is expecting to run in a full WASI environment.

feat: Add `EXTISM_ENABLE_WASI_OUTPUT` to inherit stdout/stderr

---

ocaml/Makefile
ocaml/bin/dune
ocaml/bin/main.ml

`extism-call` is a test program using the OCaml SDK, this PR adds the missing flags to make it a little more useful for general testing/

feat(ocaml): add missing flags to `extism-call` executable

---

browser/src/context.ts
browser/src/plugin.ts

Allows for initializing an extism plugin from a `WebAssembly.Module` like:
```js
const ctx = new ExtismContext();
const p = await ctx.newPlugin(new WebAssembly.Module(wasm), []);
```

feat(browser): Allow Initialization of Plugin from WebAssembly.Module

---

.github/workflows/release.yml

Add a "latest" snapshot that other libraries can use to test against the latest version of Extism.
Add caching for builds triggered by pushes to `main`.

feat(build): Add "latest" snapshot builds

---

.github/workflows/release.yml
Cargo.toml
extism-maturin/Cargo.toml
extism-maturin/build.rs
extism-maturin/pyproject.toml
extism-maturin/src/extism.c
extism-maturin/src/lib.rs

Build the python native library along with libextism since they change at roughly the same rate; we can pull the resulting wheels into python-sdk as needed.
Reduce the release job into a single matrix of `OS x RUST TARGET` – this unifies the macos, windows, and linux builds into a single job.
---
**BREAKING CHANGE**: This changes the trigger for the release workflow. Instead of being triggered by the creation of a release, it is triggered by pushing new git tags. It will catch `v*` – `v0.5.0`, `v200.0.1-dev` for example. The workflow creates a draft release.

feat(build): add extism-maturin wheel builds

---

.github/workflows/release.yml
.gitignore
extism-maturin/build.rs
extism-maturin/pyproject.toml
extism-maturin/src/extism.c

Maturin on Windows struggles with GNU headers. Since we have windows MSVC wheel builds, this commit disables windows GNU wheel builds.
Also: fix a bug where the produced wheels did not include any extism functions.

fix(build): remove windows gnu wheel builds

---

manifest/src/lib.rs
runtime/src/current_plugin.rs
runtime/src/plugin.rs
runtime/src/sdk.rs
runtime/src/tests.rs

- Removes restrictions around when `memory.max_pages` setting can be used. Before we used `wasmtime::MemoryLimiter` it was hard to determine how much was being allocated at runtime, so we used to calculate the totals statically, which required every module to have a maximum memory set at compile time. This PR allows `memory.max` to be used on any module!
- Fixes a crash when the `memory.max_pages` field is set
- Adds a test that checks for failure when allocating more than configured

cleanup(runtime): remove restrictions around `memory.max_pages` option, fix crash

---

libextism/Cargo.toml
runtime/Cargo.toml
runtime/src/current_plugin.rs
runtime/src/internal.rs
runtime/src/plugin.rs

- Updates to wasmtime 13.0.0 as the lowest supported version
- Removes `wasmtime-wasi-nn` support because it now takes parameters to specify particular backends and registries during initialization. Since I don't think anyone is using the `nn` feature I chose to remove it for now, but we could also expand the manifest to add these options.

chore: bump wasmtime lower bound to 13.0.0, remove wasi-nn support

---

.github/workflows/release-elixir.yaml

This is 404ing for some reason. But Elixir doesn't need the shared library so i'm removing it.
https://github.com/extism/extism/actions/runs/6425026823/job/17446865267

chore: fix elixir release action

---

.github/workflows/release-python.yaml

This changes the workflow slightly: whenever we publish a draft release, download our `*.whl` assets from that release and publish them to PyPI.

feat(build): GHA release-python now releases extism_sys packages

---

.github/workflows/release.yml

An update to `ring` broke the maturin-extism builds. Tracked this down to [1]; the maintainers of `ring` don't intend to support linux sysroots that old. This PR updates the ARM Linux builds in particular to pull in a newer manylinux target. Tested on a [private fork](https://github.com/extism/dev-extism/actions/runs/6644247344) of the extism repo.
[1]: https://github.com/briansmith/ring/issues/1728

fix(release): bump maturin manylinux floor  for ring 0.17 dep

---

runtime/src/plugin.rs

We should go through some of the main ones people will be interacting with and make sure there is a little more description of how to use it.

docs: Add some documentation for plugin.call

---

c/main.c
runtime/README.md
runtime/benches/bench.rs
runtime/examples/readme.rs
runtime/extism.h
runtime/src/current_plugin.rs
runtime/src/function.rs
runtime/src/plugin.rs
runtime/src/plugin_builder.rs
runtime/src/sdk.rs
runtime/src/tests/runtime.rs

Fixes #545 
- Adds a type parameter to `UserData` type to avoid dynamic typing issues
- Adds KV example from README to `examples/readme.rs` to make sure it stays in-sync
- Implement `Default` for `UserData<T>` when `T` implements `Default`
- Make `UserData` argument non-optional in `Function::new`, `UserData::default()` can be used instead.

refactor!: Cleanup UserData implementation, update example in README

---

.github/workflows/release.yml
Makefile
c/Makefile
libextism/Cargo.toml

* libextism is now built to crate-type `staticlib` as recommend by @zshipko
* updated `Makefile` to install and uninstall the static library.
* updated c example to have `static` target to link libextism statically
* Compiler is no longer hardcoded to `clang`. Set `CC` to use a compiler other than the system compiler. Tested with `gcc` and `clang`.
* added `static-artifact` to actions release. Untested as it's only ran on push with tag.

feat: build static libextism

---

runtime/src/current_plugin.rs
runtime/src/plugin.rs
runtime/src/sdk.rs
runtime/src/tests/runtime.rs

We were updating the epoch deadline callback after the call has ended to ignore any timeouts that might happen when reading output, which would allow for the plugin to be cancelled successfully the first time a plugin is called but would fail after the first call. This PR fixes cancellation by resetting the epoch deadline and callback before each plugin call.
I tested this against the dotnet sdk tests, where this was discovered, and added a similar test to the runtime test suite,
Fixes #556

fix: set epoch deadline before each plugin call

---

runtime/README.md
runtime/src/function.rs
runtime/src/lib.rs

This will help simplify writing the types for host functions, `PTR` can be used for any arguments that will point to Extism memory instead of `ValType::I64`

cleanup: add PTR as an alias for ValType::I64

---

Cargo.toml

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```

chore: fix cargo resolver warning

---

manifest/Cargo.toml
manifest/src/lib.rs
runtime/README.md
runtime/benches/bench.rs
runtime/src/plugin.rs
runtime/src/plugin_builder.rs
runtime/src/tests/runtime.rs

- Removes `Plugin::new_with_manifest` and updates `Plugin::new` to take wasm bytes or `Manifest` using the new `WasmInput` trait
- Removes `PluginBuilder::new_with_module` in favor of a `PluginBuilder::new` with a `WasmInput` argument

refactor!: allow `Plugin::new` to take raw wasm or `Manifest`

---

libextism/Makefile

I realized the glibc static build does actually work (though prints warnings at compile time), so I made it no longer hard-coded to the compiler. It's still a bad idea, so I added notes for why you shouldn't do it with glibc.

fix: libextism - make fully static target no longer hardcoded to musl-gcc

---

libextism/CMakeLists.txt

This enables cmake in-tree builds with libextism such as with the cpp-sdk: https://github.com/extism/cpp-sdk/pull/7

feat: add add_subdirectory compatible cmake config

---

runtime/Cargo.toml
runtime/build.rs
runtime/src/current_plugin.rs
runtime/src/lib.rs
runtime/src/pdk.rs
runtime/src/plugin.rs
runtime/src/sdk.rs
runtime/src/tests/runtime.rs
runtime/src/timer.rs

My initial goal was to make logging configurable for each plugin instead of global but wasn't able to accomplish that in this PR (still looking into it)
- Switches from `log4rs` to `fern` - this significantly simplifies the logging code 
- Also considered `simplelog`
- Adds `plugin.id` to the logs whenever available
- Uses `extism::plugin::$id` target for functions logged from the PDK

cleanup: simplify logging, include plugin ID in log messages

---

Cargo.toml
convert/Cargo.toml
manifest/Cargo.toml

Attempts to address an error seen when upgrading both Rust PDK & SDK to latest:
```
Updating git repository `https://github.com/extism/extism.git`
Updating git repository `https://github.com/extism/rust-pdk.git`
Updating crates.io index
error: failed to select a version for `base64`.
... required by package `extism-convert v0.2.0 (https://github.com/extism/extism.git?branch=main#7636c873)`
... which satisfies git dependency `extism-convert` of package `extism v1.0.0-alpha.0 (https://github.com/extism/extism.git?branch=main#7636c873)`
... which satisfies git dependency `extism` of package `proto_core v0.22.4 (/Users/miles/Projects/proto/crates/core)`
... which satisfies path dependency `proto_core` (locked to 0.22.4) of package `proto_cli v0.22.0 (/Users/miles/Projects/proto/crates/cli)` …
```

chore: loosen dependency requirements for base64

---

convert/src/encoding.rs

Implement `From<T>` and `Debug` for `Base64<T>`, `Json<T>`, `Msgpack<T>` and `Protobuf<T>`

Implement convenience traits for encoded types

---

.github/workflows/release.yml
Cargo.toml
convert/Cargo.toml
extism-maturin/Cargo.toml
libextism/Cargo.toml
manifest/Cargo.toml
runtime/Cargo.toml

This is an attempt to sand down [a sharp edge](https://github.com/extism/extism/actions/runs/6949120346/job/18906546065#step:4:476) around releases – keeping the `Cargo.toml` versions in-sync with the release tag, & the versions of the workspace crates aligned with one another.

build: drive crate versions from workspace; drive workspace version from ci

---

.github/workflows/release-convert.yaml
.github/workflows/release-manifest.yaml
.github/workflows/release-rust.yaml
extism-maturin/Cargo.toml

Follow-up to f7d297f98f4b75bdce969afd946c459916402b8f.
Update the release workflows for the dependent crates. The Cargo workflows run on GitHub release publish to match the Python package release workflow. This means all of our crates are versioned in lockstep by the Git tag.
There are four changes:
1. Trigger the workflows on GitHub release publish
2. Add the `set version` step from `release.yml` to modify the version tags in `Cargo.toml`.
3. Publish with `--allow-dirty` (to account for the edit in step 2)
4. In `extism-maturin`, do not inherit `authors` from the workspace since [PyPI rejects the value we have set](https://github.com/extism/extism/actions/runs/7012534645/job/19077216730#step:7:23).

build: drive cargo releases from git tag

---

runtime/src/manifest.rs
runtime/src/plugin.rs

This PR simplifies the resolution of the `main` module when multiple modules are provided. Before we would try to look at the path/URL when the wasm was coming from disk or via HTTP, now any module missing a name will be used as `main`. This is much nicer and more consistent since this is what was being done when no filename was available (i.e. raw data modules). It also make sense because non-main modules will need to be named for the functions to be linked correctly.

cleanup: simplify main module resolution

---

runtime/src/manifest.rs

As pointed out by @mtb0x1 in https://github.com/extism/extism/commit/af4fd184e6ef9955403d573520619e91a5003959#r133737418

cleanup: avoid matching meta.name twice

---

runtime/README.md

Fix link to Manifest in the Rust/Runtime README

fix manifest link

---

convert/src/encoding.rs
runtime/src/function.rs
runtime/src/plugin.rs
runtime/src/tests/issues.rs
runtime/src/tests/runtime.rs

Fixes #619  
- Also updates `host_fn`, `encoding`, and `typed_plugin` macros to allow for visibility specifiers to manage the visibility of the defined types. This means that `pub` will need to be added to existing invocations that should remain public

refactor!: better scoping of arguments in host_fn macro, allow visibility in macros to be specified 

---

runtime/build.rs
runtime/extism.h

Before `extern "C"` was needed to include the header in C++ code. Now that's included inside, so it's easier and cleaner to include in c++ projects like the `cpp-sdk`.

build: add c++ compat to extism.h

---

convert/Cargo.toml
convert/src/encoding.rs
convert/src/lib.rs

- Adds `extism_convert::Raw` to encode certain types using their direct memory representations using https://github.com/Lokathor/bytemuck
- Only enabled on little-endian targets to prevent memory mismatch issues 
- Allows for certain types of structs to be encoded using their in-memory representation
- Makes passing structs between Rust and C easier since none of the other encodings are available in C by default.
After making a bytemuck-compatible struct:
```rust
use bytemuck::{Zeroable, Pod};
#[derive(Debug, Clone, Copy, PartialEq, Pod, Zeroable)]
#[repr(C)]
struct Point {
x: i32,
y: i32,
}
```
It can be used in `call`:
```rust
let input = Point { x: 100, y: 50 };
let Raw(pt): Raw<Point> = plugin.call("transform", Raw(&input))?;
```

feat: Add `extism_convert::Raw` to allow direct encoding using bytemuck

---

.github/workflows/release.yml

Related to #141 and #584 
Follow up of #632

ci: release extism.dll.lib and extism.dll.a

---

runtime/extism.h
runtime/src/sdk.rs

This fixes a test failure on the python-sdk [1]. (See also [2]). In particular, while maturin creates bindings for `extism_log_drain` on clang platforms, it seems that MSVC cannot generate the required binding information for `ffi.py`. This results in an `extism_sys` wheel whose shared object (in this case, a DLL) contains the `extism_log_drain`, but whose Python FFI bindings don't contain a definition for that function.
Naming the function pointer type parameter resolves the issue. What a strange issue!
[1]: https://github.com/extism/python-sdk/actions/runs/7172934060/job/19669775001#step:9:35
[2]: https://github.com/extism/python-sdk/pull/18#issuecomment-1850892835

fix: give extism_log_drain's param a named type

---

manifest/src/lib.rs

The default for `timeout_ms` is currently 30s which was an arbitrary decision but it forces a user to set `timeout_ms` to null to avoid having plugins cancelled which is a little strange.

cleanup: remove default timeout

---

runtime/Cargo.toml

The only feature for `cbindgen` is the `clap` feature for using it as a standalone binary and isn't needed when using it as a library

Toggle off default `clap` feature for `cbindgen`

---

runtime/src/plugin.rs

- Adds `Plugin::call_get_error_code` to get the Extism error code when a call fails

feat: add `Plugin::call_get_error_code` to get Extism error code along with the error

---

runtime/src/manifest.rs

- Update to ensure `is_wat` is only true when the input is a valid string
- Update to allow leading whitespace in a wat file

cleanup: improve wat detection

---

runtime/src/manifest.rs

Merged the other one too quickly, this PR is updated with some additional feedback from @chrisdickinson:
(Ooh, this could also start with `(;`)
https://github.com/extism/extism/pull/650#discussion_r1443419249
It's also updated to accommodate for modules that start with an open paren followed by some whitespace. I doubt this covers all of the permitted syntax but it should be good enough.

cleanup: improve wat detection (again)

---

convert/Cargo.toml
convert/src/encoding.rs
convert/src/lib.rs

(code from @zshipko, thank you!)

feat: add rust-protobuf support to extism-convert

---

manifest/schema.json
manifest/src/lib.rs
runtime/src/tests/runtime.rs

base64 support is retained. Now `data` can instead be `{"ptr": ptr_value, "len": len_value}` where `ptr_value` points to a wasm module and `len_value` is the size of bytes of it.

feat: manifest wasm data without base64

---

runtime/src/plugin.rs

This PR addresses #654
It checks the parameters and results of the function as described in the mentioned issue.

Make function Plugin::function_extists check the type of the functions.

---

manifest/schema.json
manifest/src/lib.rs
runtime/src/pdk.rs

- Adds `memory.max_http_response_bytes` field to specify the maximum size of an HTTP request response

feat: allow max HTTP response size to be configured in the manifest

---

runtime/src/plugin.rs
runtime/src/tests/runtime.rs

It looks like when a module is added to the linker, all of its imports must already be present. This PR updates the linking process to take that into consideration and adds a test with a reproduction of the issue @chrisdickinson shared with me.

fix: linker issue that depends on the ordering of the linked functions

---

manifest/schema.json
manifest/src/lib.rs
runtime/src/pdk.rs
runtime/src/tests/runtime.rs

- Adds `memory.max_var_bytes` to the manifest to limit the number of bytes allowed to be stored in Extism vars - if `max_var_bytes` is set to 0 then vars are disabled.
- Adds some builder functions to `MemoryOptions` struct
- Sets the default var store size to 1mb
- Includes a test to make sure `var_set` returns an error when the limit is reached

feat: add ability to configure size of the Extism var store

---

README.md

Still under-representing, but a better representation of Extism downloads

chore: update badge to reflect rust installs

---

runtime/examples/linking.rs

Just adding more context in response to an inquiry about how this works.

docs: Add more context to linking example

---

runtime/src/current_plugin.rs
runtime/src/internal.rs
runtime/src/pdk.rs
runtime/src/plugin.rs
runtime/src/tests/runtime.rs

Currently HTTP requests can extend beyond the configured timeout for a plugin - this PR sets the timeout of the HTTP request to the remaining time left if a timeout is set in the manifest.

fix: respect overall timeout when using http requests

---

runtime/Cargo.toml
runtime/src/current_plugin.rs
runtime/src/function.rs
runtime/src/internal.rs
runtime/src/plugin.rs
runtime/src/sdk.rs

- Breaking: No longer copies Extism config values into WASI environment variables because the new interface doesn't allow for the environment to be updated - these should be accessed using the Extism config functions instead
- Requires wasmtime 20 or greater
- Enables wasm-gc
- Similar to https://github.com/extism/extism/pull/697 without sockets or additional support for command modules

refactor!: update to wasmtime 20 or greater

---

runtime/src/plugin.rs

Returns an error when a plugin call returns a non-zero exit code
See https://github.com/extism/go-pdk/issues/33

fix: return error when non-zero exit code in returned

---

Makefile
libextism/Makefile
libextism/example.c
libextism/extism-static.pc.in
libextism/extism.pc.in
runtime/Cargo.toml

This includes two fixes:
* link static library by absolute path (should fix static linking on Mac/ with `lld`)
* link `libpthread` , this should be a no-op on systems with modern libc, but should fix static linking on systems with glibc pre 2.34 see https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread and error http://www.cpantesters.org/cpan/report/669fdfc8-25a4-11ef-9502-51fb6d8775ea
@zshipko if you could verify `make pkg-config-static` and the resulting `example` executable in `libextism` works on Mac that would be greatly appreciated.

fix(libextism): improve static linking pkgconfig

---

runtime/src/plugin.rs
runtime/src/sdk.rs

Related to https://github.com/extism/python-sdk/issues/23 - there is currently no way to get the length of the error message, so we need to make sure it is a valid C string.

fix: require error messages to be null terminated in C SDK

---

runtime/extism.h
runtime/src/lib.rs
runtime/src/pdk.rs
runtime/src/plugin.rs
runtime/src/sdk.rs

In addition to this change, @zshipko is looking into if we need to extract basic log level info from the more complex `filter` string, and how to require `tracing` compatibility to at least set some level (or to work when there is no level set thus ignoring all logs)
For other runtimes, there is still an equivalent implementation for `get_log_level() -> I32`  in Go and JS, as well as the ability to set the log level for the host, which is then loaded when `get_log_level` is called. 
TODO:

feat(runtime): add log level set/get for pdk control

---

runtime/src/current_plugin.rs
runtime/src/plugin.rs
runtime/src/sdk.rs
runtime/src/tests/runtime.rs

Updates plugins to allocate a single `ExternRef` for the host context up front, to avoid running into the `failed to allocate externref` error from Wasmtime

fix: avoid creating too many externrefs

---

runtime/src/current_plugin.rs
runtime/src/lib.rs
runtime/src/plugin.rs
runtime/src/sdk.rs

- Checks error results to determine if a plugin ran out of fuel, if the fuel is 0 after we get the error, then we return an out of fuel error message instead.
- Updates `extism_plugin_error` to check `Plugin::error_msg` regardless of the kernel's error state

fix: better error handling when plugin runs out of fuel

---

runtime/src/plugin.rs
runtime/src/plugin_builder.rs
runtime/src/sdk.rs

An alternative to #763, this PR allows an initial `wasmtime::Config` to be passed in when building a plugin. Some of these values may be overwritten by the Extism runtime, but it allows for things like static memory size and other low-level details to be handled directly instead of us having to wrap every option ourselves.

feat: add `PluginBuilder::with_wasmtime_config`

---

runtime/src/pdk.rs

think there's a typo for this block when the `http` feature is disabled

Fix: no method named `free` found for mutable reference `&mut current_plugin::CurrentPlugin` in the current scope

---

runtime/src/sdk.rs

fix: use `f32::to_bits` and `f64::to_bits` when constructing `Val`

---

runtime/examples/fs.rs

Since it's using a read-only path, we should provide some information about how to use a read/write path to make this program run without failing.

docs: add comment to fs example

---

.github/workflows/release-dotnet-native.yaml

This makes sure the latest releases are always available on NuGet too

Trigger NuGet package publishing when a new release is published

---

runtime/src/plugin.rs
runtime/src/sdk.rs

Closes https://github.com/extism/extism/issues/801
Updates the error from:
```
Unable to compile Extism plugin: incompatible import type for `extism:host/user::wrong_type`
```
to:
```
Unable to compile Extism plugin: types incompatible: expected type `(func (result i32))`, found type `(func (result i64))`
```

fix: improve sdk error messages around imports

---

runtime/src/plugin.rs
runtime/src/tests/runtime.rs

This PR adds a function to get the fuel consumed by a plugin. This is useful for systems that want to fairly balance compute. It's my first time doing anything in rust so let me know if something needs improvements!

feat: added a function to track fuel consumption

---

.github/workflows/release.yml
runtime/src/timer.rs

Fixes an issue reported on discord (https://discord.com/channels/1011124058408112148/1154513155209298041/1329622656235864156) where the timer thread is taking up an entire CPU

cleanup: stop timer from using 100% cpu when no timeouts are set

---

runtime/Cargo.toml
runtime/src/current_plugin.rs
runtime/src/plugin.rs

Upgrades from wasmtime 26 to wasmtime 27-29, allowing us to support more versions (including the possibility of supporting future releases without changes)

chore: update wasmtime bounds to include more versions

---

.github/dependabot.yml
runtime/Cargo.toml

Also updates dependabot config to bundle wasmtime updates so this can be done automatically in the future.

chore: include wasmtime 30 in supported bounds

---

runtime/README.md

I know that there is already a logging example in `runtime/examples/log_callback.rs` but I think that's not where people go to look to figure out how the logging functionality works. At least for me that wasn't the case :)

doc: explain how to see plug-in logs

---

convert-macros/src/lib.rs

Here is a code snippet that demonstrates the issue:
```rust
use extism_pdk::{encoding, plugin_fn, FnResult, FromBytes, Json, ToBytes};
use serde::{Serialize, Deserialize};
#[derive(Deserialize,FromBytes)]
pub struct Input {
value:String
}
#[derive(Serialize, ToBytes)]
pub struct Output {
value: f64,
}
#[plugin_fn]
pub fn convert(in_value: Input) -> FnResult<Output> {
Ok(Output { value: in_value.value.parse().expect("Conversion failed") })
}
```
Because the structs don't derive `encoding` the rust-analyzer gives this suggestion:
```
encoding needs to be specified
= try: `#[encoding(ToJson)]`
```
I don't think this suggestion is correct because i could not find `ToJson` anywhere. Adding  `#[encoding(Json)]` solves the issue (as described in the docs). 
The final code would look as follows: …

fix: better suggestion when encoding is not implemented

---

.github/workflows/release-dotnet-native.yaml

It seems like at some point we changed the `release.yml` workflow to create multiple artifacts instead of one `release-artifacts` tarball. I changed the .NET Nuget workflow to be more like Python

fix: use gh release download instead of downloading from github action artifacts in dotnet workflow

---

runtime/Cargo.toml
runtime/src/lib.rs
runtime/src/plugin.rs
runtime/src/plugin_builder.rs
runtime/src/pool.rs
runtime/src/tests/mod.rs
runtime/src/tests/pool.rs

- `Pool` allows for a configurable number of instances for each plugin and will block waiting for a plugin to become available if the limit is reached

feat: add Pool type for pooling plugin instances

---

runtime/Cargo.toml

This PR disables all possible dependencies for wasmtime, while the code can still compile. Its possible that some of these removed features should be enabled again if they help with debugging or improve performance. [Here](https://github.com/bytecodealliance/wasmtime/blob/v31.0.0/crates/wasmtime/Cargo.toml#L129) you can see all the default features, as well as documentation for each feature flag. 
It reduces the number of dependencies from 401 to 366. I didnt check the compile time but it should also be faster.

Disable unused wasmtime features

---

runtime/src/pdk.rs

fix: set ureq http_status_as_error to false to allow access to headers/body of non-200 responses
